fix: report uploader
redhat-marketplace/redhat-marketplace-operator pull request #350
Opened 2022-07-14 13:55 UTC by MJSiddu

Ticket:
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25629

Changes:
- Updated upload task to delete the file from DataService only when the backend upload was successful.

2022-07-15 14:33 UTC, mxpaspa submitted a review, later dismissed

2022-07-18 09:46 UTC, ab-ibm requested changes

2022-07-18 09:46 UTC, ab-ibm commented on reporter/v2/pkg/reporter/upload_task.go
>  	}
let's add some log entry that file will be not deleted

2022-07-19 06:29 UTC, ab-ibm approved these changes

2022-07-25 13:51 UTC, MJSiddu commented
Closing this PR as I have included this code in PR https://github.com/redhat-marketplace/redhat-marketplace-operator/pull/354

2022-07-25 13:51 UTC, closed without merging