feat: deprecate rhm prometheus
redhat-marketplace/redhat-marketplace-operator pull request #373
Opened 2022-10-14 18:50 UTC by dacleyra

- remove go-health due to unresolvable deps. use of was not fully implemented anyways.
- Allow an upgrade from v2.x -> v2.9.0 to continue using RHM Prom (until vnext)
- Disallow a new v2.9.0 install from creating RHM Prom, must use UWM
- Operator: Log a deprecation warning message if RHM Prom is being used (upgrade users), and that they should transition
- Operator: Generate an Event warning message if RHM Prom is being used (upgrade users), and that they should transition

2022-10-17 10:06 UTC, ab-ibm commented
@dacleyra if UWM is not enabled, rhm-data-service-0 stuck in ContainerCreating state until customer enables UWM, is this as expected?

2022-10-17 13:00 UTC, ab-ibm requested changes

2022-10-17 18:56 UTC, ab-ibm commented
Tested:
- clean installation
- upgrade with UWM enabled
- upgrade with RHM Prometheus

2022-10-18 19:32 UTC, dacleyra commented on v2/controllers/marketplace/meterbase_controller.go
> +			r.recorder.Event(instance, "Warning", "PrometheusDeprecated", "Use of redhat-marketplace-operator Prometheus is deprecated. Configure user workload monitoring https://marketplace.redhat.com/en-us/
error stack is normal since this is a presented as a reqLogger.Error() when UWM is not enabled on a new install

2022-10-19 06:43 UTC, ab-ibm approved these changes

2022-10-19 18:36 UTC, mxpaspa approved these changes

2022-10-19 19:34 UTC, merged